supabaseUrl: "postgresql://postgres:postgres@localhost:5432/postgres"
supabaseRealtimeUrl: "wss://localhost:5432/realtime/v1/websocket"
supabaseAnonKey: "replace-with-actual-anon-key"
pathToDockerCompose: "./config/docker-compose.yaml"
frontendServiceName: "frontend"
frontendContainerName: "frontend"
backendServiceName: "backend"
backendContainerName: "backend"
statsServiceName: "stats"
statsContainerName: "stats"
table: "silos"
chainId: "replace-with-actual-chain-id"
# When the following is set, docker-compose will be left as is and instead the common environment file will be updated
pathToCommonEnvironmentFile: ""
